language: R
cache:
packages: true
directories:
  - inst/examples/_book

before_install:
  - nvm install stable
  - npm install netlify-cli -g

deploy:
  provider: script
  before_script: cd inst/examples
  script:
    - Rscript -e 'bookdown::render_book("index.Rmd")'
    - netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN --prod --dir _book
  skip_cleanup: true
